### ISSUE TITLE
updated

### ISSUE THREAD

**Issue by whiz123** [ThijmenGThN/EasyEco#3]
Shop (Most Important)
Have a shop that server owners can config to setup can buy items that give roles in return! 
Config; Prices! and enable the shop command or disable it for the server.

Factions are now changed to Guilds
Make sure the guilds can be active or inactive depending on how the server owner feels.
**Guild banks and the guild bank price (IMPORTANT)**

**Comment by ThijmenGThN** [comment]
Part 2 has been forwarded to a different submitted issue.
